travis:
  secure:
    BINSTAR_TOKEN: cmfqhnt9z8zLausLG1t7WGDTO0LzH+bFrQyHAN5P/Fa0d/Lxeeyf4dZ3hUN6ONVPPzJjz29uLUU33frbHdSAvS0ju2cdx0ho0pt1RaYc+phAwW+c6hg+0d9WRlDu4cVGuW772EWMnnig0r+GEV5okRnq7DGHhFHkOVb8EHbGETniAkdw2ET+mnc/QyheY+SA+H2TpqaLA1KwnY8kbl74mkg7KPA0FsfoNOKkB4pIb+7gpyslwJBE3nBg7hXljmZFbpz/9evBquzZwpTYAmsPbTHM6cQZvpeun1JGh8XqrSN0hAxto5/AaF0BvNCQtKXO8QbwKtV2eFTE6pW3LLF89ndqL7G1kS/bxzCR6CW9R5DRLxKoazaLB6EJCsUmkzQSGS/P6WyvPwX/bIK/zfp+Qf/TM3e3SuQ2VY5xex7h50lGEkgCa0grdlpWQjUH2VjCTutkR4utXtNe4ZTJDumr9B942ZcsunGyZQdyAdfvrQq3v0pph35eoAs7ypAEpjQknvl9NjHaAVPoNBrl8cS9VDgfGRZ4mbRm1fkf7SwdFWEL0w/btrEfl7V1Xyxm17ywmP4g1hb0tQvHMohxdejQ9+SLboyiXIrpTh7dpf/sxCpdncOoLwYZoMeTbYSp27u9JjdJPXAlruNOWLad3qhuW5l2z1F5S/eSXEXJE0WM1/E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
