travis:
  secure:
    BINSTAR_TOKEN: dTH9TVJeD/66oEiZyFzU62d+CRv5EBAHuwb1va+Dp5IYNRhDyrQIwcxoJRlnc8puB2fRe+fj08nMmpNNilffpK584Lw2xFC3vMf5EhQB3TjTrjMkU0gpWm53K6ezYBvzdqelrdohNZTKEHkQcNFedfzZEAnWPnIvdVn8UgvKLtel4j6guMlLcx8jug6vWRFXRGg1F0F1lfxr4oMkl7/YJBYt77HVLELeTTTtR/9xdjtWM4GrvTHOMp/62nefxwnFPKqgAeTyL+ggJr3hrt9gvDWJLp/gLxR7ZHxTNJm8Fwr3hXJAER/R8bokhtu253ISrAwt2zqmMAvImN1yMDrL/frKnhfW9XCwH6dY8OcLqnjjX8JqKGPVXZtgTx89jKIdwjRD+nK/deNWrFMXLRFTgp/Ix64GbmkeTnfGFYCVYBxsnuwyjnRoMSYtQFtu8N1SJ+9beH34g5xOlsPM6qsvu5RXWh9CTtsvt65dVa8LIeUjIkQxR9xPldaUxiUwaOzTdoEnE0hGeOmKGhoG0s0IsSoGcZT45jUkmrYnkNU6quIpTYI45BDT6HRMPoOnd3m/RCjaEIKEb/iLzxMrOgMPiA2BuIXHTk1mFv4Oj0ZcTHjGcVO+n8XyI71sB/1lk8EbAvuO4BkqyR6AojpFCVIaQderGamgtg4dIW3Lxrnhikc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
