travis:
  secure:
    BINSTAR_TOKEN: uNnpZkmZa8z9ADaCuBwP0W4h9JOIl66sfA+6uiSGzhI05wF0HzGjKcvFA4Ddzc8v/Ms1B96TPLrse3RP1JMnGCa1HfnPAw9izSsbvfZErPO1e7tZ5JtybXPcs7x0ytTkIZEind5MdWmBrotHfvo2WqQrSLFrR+ka5ShCKh72q9qbCo8VzjwfenmxzndAiTFDRDxgHqNaBL2CjHWmVRjThHeJMXSBguZxB7eJT8PGSG6FbHrlNk8Ipey77DJOkPUMuYfUAZRa0LMdy5sC3n+zn+eTJAZsDjAMbzU9QAX+gO5fihSGbiHTgSI5LpEjzT5hNrhiY7Ja4ZVOKlnTna4EQO12Q06pr7sR0dQ5pOVBkHGWhZm95WO1ZPFTDo90NrxcqG8NZrngM7F+XrKIi4Uzq97gkdbekg0NsLr/c7awLFjB/txMKqOvl2g1uaEce5fHQlmH/alSag8/WvIekzaE6xIRBve7gOIKnq+GXW51/0XHjg/eyoSzZ0dz7y0chOrQLr5VyG2J6rYAHhe3a2d1C+VTcWQxyOlFra/GEG1IoslPI5Q1YkiAOKjiQPisf8D/5HQljgmLYudiPuQ7RWQ0oHN4fqgjW8rJD5FSOuNML+4euKxV+Xf3HIKxwSkbrfimoBRMavtiCLzNzUJ3y6/eC02JSGox0jpL2aB18XZizkw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
